name: "food101" # task name, used to process title and save dir name
label_config: "configs/label_config.txt"

is_dataset_cached: false
dataset_cache_dir: ""  # datasets module save cache path, if is_dataset_cache is false, it does not take effect

model:

processor:
  type: transformers,ViTImageProcessor
  args:



train_args:
  #! Optional: transformers.TrainingArguments
  output_dir: null # if not set, will using outputs/`name`
  eval_strategy: "epoch"
  per_device_train_batch_size: 128
  per_device_eval_batch_size: 32
  save_strategy: "epoch"
  logging_steps: 10
  weight_decay: 0.0001
  num_train_epochs: 500
  learning_rate: 0.0001
  logging_first_step: true
  remove_unused_columns: false  #! importance! This is must be false. Because our data will be load when training. If we remove unused_columns, we will not any data
evaluate_metric:
  #! Optional: `evaluate package` could load.  some metric need special process.
  - "accuracy"
  - "recall"
  - "precision"
  - "f1"

train_dataset:  # train_dataset configure
  type:  src.dataset,Dataset # used class name, format `{module_name},{class_name}`
  args:  # class args
    data_paths:
      - configs/train.txt  # data_path  Currently only .txt format is implemented `{img_path}\t{label}`
    # albumentations:  # Data Enhancement, if you don't need this, your yaml not be write this key
      # more data enhancement see https://pypi.org/project/albumentations/
      # - type: albumentations,RGBShift
      #   args:
      #     r_shift_limit: 
      #       - -20
      #       - 20
      #     g_shift_limit:
      #       - -20
      #       - 20
      #     b_shift_limit:
      #       - -20
      #       - 20
      #     p: 0.5
      # - type: albumentations,HueSaturationValue
      #   args: null
      # - type: albumentations,ChannelShuffle
      #   args: null
      # - type: albumentations,CLAHE
      #   args: null
      # - type: albumentations,RandomBrightnessContrast
      #   args: null
      # - type: albumentations,RandomGamma
      #   args: null
      # - type: albumentations,Blur
      #   args: null

validation_dataset:
  type: src.dataset,Dataset
  args:
    data_paths:
      - configs/validation.txt



